COMMON_NETWORK: 
  default:
    external:
      name: homelab-network
COMMON_DATASTORE: '/data'
COMMON_CERT_BASE: '/data/secrets'
  
CA_CERT: '{{ COMMON_CERT_BASE }}/ca.crt'
CA_PRIVATEKEY: '{{ COMMON_CERT_BASE }}/ca.pem'

ARTIFACTORY_PORT: 8090
ARTIFACTORY_NETWORK: '{{ COMMON_NETWORK }}'

CONSUL_NETWORK: '{{ COMMON_NETWORK }}'
CONSUL_SERVER: 8300
CONSUL_SERF_LAN: 8301
CONSUL_SERF_WAN: 8302
CONSUL_HTTP: 8500
CONSUL_DNS: 8600

GITEA_NETWORK: '{{ COMMON_NETWORK }}'
GITEA_HTTP_PORT: 3000
GITEA_SSH_PORT: 10022
GITEA_ADMIN_NAME: 'root'
GITEA_ADMIN_PASS: 'test'
GITEA_ADMIN_EMAIL: 'example@example.com'

JENKINS_NETWORK: '{{ COMMON_NETWORK }}'
JENKINS_HTTP_PORT: 8080
JENKINS_SLAVE_PORT: 50000
           
SAMBA_NETWORK: '{{ COMMON_NETWORK }}'
SAMBA_LDAP_PORT: 389
SAMBA_LDAPS_PORT: 636
SAMBA_ADMIN_PASS: 'TopS3cr3t'
SAMBA_CRT: '{{ COMMON_CERT_BASE }}/ldap.crt'
SAMBA_PRIVATEKEY: '{{ COMMON_CERT_BASE }}/ldap.pem'
SAMBA_CA: '{{ CA_CERT }}'

LDAP_ADMIN_NETWORK: '{{ COMMON_NETWORK }}'
LDAP_ADMIN_HTTP: 8083
LDAP_ADMIN_HTTPS: 8084
LDAP_ADMIN_CRT: '{{ COMMON_CERT_BASE }}/ldap-admin.crt'
LDAP_ADMIN_PRIVATEKEY: '{{ COMMON_CERT_BASE }}/ldap-admin.pem'
LDAP_ADMIN_CA: '{{ CA_CERT }}'
LDAP_ADMIN_PASSWORD: '{{ SAMBA_ADMIN_PASS }}'
LDAP_ADMIN_CONFIG:       
  - 'ldap':
    - server:
      - tls: true
    - login:
      - bind_id: 'cn=administrator,cn=users,dc=example,dc=com'
      - bind_pass: '{{ LDAP_ADMIN_PASSWORD }}'

NEXUS_NETWORK: '{{ COMMON_NETWORK }}'
NEXUS_HTTP_PORT: 8081
NEXUS_HTTPS_PORT: 8443
NEXUS_DOCKER_PORT: 9082
NEXUS_ADMIN_PASSWORD: 'test'
NEXUS_LDAP_SERVER: 'ldap'
NEXUS_LDAP_OU: 'dc=example,dc=com'
NEXUS_LDAP_USERS_OU: 'ou=Users'
NEXUS_LDAP_GROUPS_OU: 'ou=Groups'
NEXUS_LDAP_USER: 'cn=administrator,cn=users,dc=example,dc=com'
NEXUS_LDAP_PASS: '{{ SAMBA_ADMIN_PASS }}'
NEXUS_CRT: '{{ COMMON_CERT_BASE }}/nexus.crt'
NEXUS_PRIVATEKEY: '{{ COMMON_CERT_BASE }}/nexus.pem'
NEXUS_CA: '{{ CA_CERT }}'

VAULT_NETWORK: '{{ COMMON_NETWORK }}'
VAULT_PORT: 8200
VAULT_CACERT: '{{ CA_CERT }}'
VAULT_CERT: '{{ COMMON_CERT_BASE }}/vault.crt'
VAULT_PRIVATEKEY: '{{ COMMON_CERT_BASE }}//vault.pem'
VAULT_CONSUL_ADDR: 'consul:8500'
VAULT_CONSUL_ADVERTISE_ADDR: 'http://consul:8300'