---
- name: 'Create dockerfile source'
  file:
    path: '{{ item }}'
    state: 'directory'
  with_items:
    - '{{ MAIL_IMAP_BUILD_PATH }}'
    - '{{ MAIL_WEBMAIL_BUILD_PATH }}'

- name: 'Copy dockerfile'
  copy:
    src: 'files/{{ item.name }}/Dockerfile'
    dest: '{{ item.path }}/Dockerfile'    
  with_items:
    - { name: 'imap', path: '{{ MAIL_IMAP_BUILD_PATH }}' }
    - { name: 'webmail', path: '{{ MAIL_WEBMAIL_BUILD_PATH }}' }
    
- name: 'Copy CA Cert'
  copy:
    src: '{{ MAIL_CA }}'
    dest: '{{ item }}/ca.crt'
  with_items:
    - '{{ MAIL_IMAP_BUILD_PATH }}'
    - '{{ MAIL_WEBMAIL_BUILD_PATH }}'
    
- name: 'Copy php.ini'
  copy:
    src: 'files/webmail/php.ini'
    dest: '{{ MAIL_WEBMAIL_BUILD_PATH }}/php.ini'

- name: 'Copy dovecot configs'
  template:
    src: '{{ item }}'
    dest: '{{ MAIL_IMAP_BUILD_PATH }}/{{ item | basename }}'
  with_items:
    - 'files/imap/dovecot-ldap.conf.ext'
    - 'files/imap/dovecot-logging.conf'
    
- name: 'Create containers for mail infrastructure'
  docker_service:
    project_name: '{{ MAIL_NAME }}'
    build: yes
    definition:    
      version: '3.5'
      networks: '{{ MAIL_NETWORK | default(omit) }}'
      services:
        imap:
          build: '{{ MAIL_IMAP_BUILD_PATH }}'
          image: '{{ MAIL_NAME }}-imap'
          container_name: '{{ MAIL_NAME }}-imap'
          ports:
             - '{{ MAIL_IMAP_PORT }}:143'
             - '{{ MAIL_IMAPS_PORT }}:993'
          secrets:
            - { source: 'imap.crt', target: '/etc/ssl/dovecot/server.pem' }
            - { source: 'imap.pem', target: '/etc/ssl/dovecot/server.key' }
          restart: 'always'
        smtp:
          image: 'tozd/postfix:alpine-38'
          container_name: '{{ MAIL_NAME }}-smtp'
          environment:
            - 'MY_NETWORKS=127.0.0.0/8 172.18.0.0/16'
          ports:
            - '{{ MAIL_SMTP_PORT }}:587'            
          restart: 'always'
        webmail:
          build: '{{ MAIL_WEBMAIL_BUILD_PATH }}'
          image: '{{ MAIL_NAME }}-webmail'
          container_name: '{{ MAIL_NAME }}-webmail'
          environment:
            - 'ROUNDCUBEMAIL_DEFAULT_HOST=ssl://{{ MAIL_NAME }}-imap'
            - 'ROUNDCUBEMAIL_DEFAULT_PORT={{ MAIL_IMAPS_PORT }}'
            - 'ROUNDCUBEMAIL_SMTP_SERVER={{ MAIL_NAME }}-smtp'
            - 'ROUNDCUBEMAIL_SMTP_PORT={{ MAIL_SMTP_PORT }}'
          ports:
            - '{{ MAIL_WEBMAIL_PORT }}:80'
          secrets:
            - { source: 'imap.crt', target: '/etc/ssl/certs/mail-imap.pem' }
            - 'webmail.crt'
            - 'webmail.pem'
          restart: 'always' 
      secrets:
        imap.crt:
          file: '{{ MAIL_IMAP_CRT }}'
        imap.pem:
          file: '{{ MAIL_IMAP_PRIVATEKEY }}'
        webmail.crt:
          file: '{{ MAIL_WEBMAIL_CRT }}'
        webmail.pem:
          file: '{{ MAIL_WEBMAIL_PRIVATEKEY }}'          