---
- include_vars: '{{ NEXUS_ROLE_PATH }}/defaults/main.yml'
  tags: always

- name: 'Check admin credentials'     
  uri:
    url: 'http://127.0.0.1:{{ NEXUS_HTTP_PORT }}/service/rest/v1/script'
    user: 'admin'
    password: '{{ NEXUS_INITIAL_ADMIN_PASSWORD }}'
    body_format: 'json'
    method: 'GET'
    force_basic_auth: yes
    status_code: 200,401
  register: admin_result

- name: 'Admin password was already changed'
  when: 'admin_result.status == 401'
  set_fact:
    current_nexus_admin_password: '{{ NEXUS_ADMIN_PASSWORD }}'
   
- name: 'Admin password has not been changed'
  when: 'admin_result.status == 200'
  set_fact:
    current_nexus_admin_password: '{{ NEXUS_INITIAL_ADMIN_PASSWORD }}'   

- name: 'Declare groovy scripts'
  uri:
    url: 'http://127.0.0.1:{{ NEXUS_HTTP_PORT }}/service/rest/v1/script'
    user: 'admin'
    password: '{{ current_nexus_admin_password }}'
    body_format: 'json'
    method: 'POST'
    force_basic_auth: yes
    status_code: 204,500
    body:
      name: '{{ item | basename | splitext | first }}'
      type: 'groovy'
      content: '{{ lookup("file", item) }}'
  with_fileglob: '{{ NEXUS_ROLE_PATH }}/files/groovy/*.groovy'

- name: 'Change admin password'
  when: 'admin_result.status == 200'
  include_tasks: '{{ NEXUS_ROLE_PATH }}/tasks/admin_password_setup.yml'
  vars:
    nexus_admin_password: '{{ NEXUS_ADMIN_PASSWORD }}'
    
- set_fact:
    nexus_default_port: '{{ NEXUS_HTTP_PORT }}'
    ldap_connections: 
      - ldap_name: 'Default'
        ldap_protocol: 'ldaps'
        ldap_hostname: '{{ NEXUS_LDAP_SERVER }}'
        ldap_port: 636
        ldap_auth: 'simple'
        ldap_auth_username: '{{ NEXUS_LDAP_USER }}'
        ldap_auth_password: '{{ NEXUS_LDAP_PASS }}'
        ldap_search_base: '{{ NEXUS_LDAP_OU }}'
        ldap_user_base_dn: '{{ NEXUS_LDAP_USERS_OU }}'
        ldap_user_object_class: 'user'
        ldap_user_id_attribute: 'sAMAccountName'
        ldap_user_real_name_attribute: 'cn'
        ldap_user_email_attribute: 'mail'
        ldap_map_groups_as_roles: true
        ldap_group_base_dn: '{{ NEXUS_LDAP_GROUPS_OU }}'
        ldap_group_object_class: 'groupOfUniqueNames'
        ldap_group_id_attribute: 'cn'
        ldap_group_member_attribute: 'uniquemember'
        ldap_group_member_format: '${dn}'
    nexus_roles:
      - id: Developers
        name: developers
        description: All development team
        privileges:
          - nx-search-read
          - all-repos-read
        roles: []
      - id: Operations
        name: operations
        description: All operations team
        privileges:
          - nx-search-read
          - all-repos-read
        roles: []
      - id: Engineers
        name: engineers
        description: All engineering team
        privileges: []
        roles: 
          - nx-admin
  tags: always

- include: '{{ NEXUS_ROLE_PATH }}/tasks/setup_ldap_each.yml'
  with_items: "{{ ldap_connections }}"

- include: '{{ NEXUS_ROLE_PATH }}/tasks/setup_role_each.yml'
  with_items: "{{ nexus_roles }}"

- include: '{{ NEXUS_ROLE_PATH }}/tasks/call_script.yml'
  vars:
    script_name: setup_anonymous_access
    args:
      anonymous_access: false
      
- include_tasks: '{{ NEXUS_ROLE_PATH }}/tasks/create_repo_docker_hosted_each.yml'
  with_items: '{{ nexus_repos_docker_hosted }}'

- include_tasks: '{{ NEXUS_ROLE_PATH }}/tasks/create_repo_docker_proxy_each.yml'
  with_items: '{{ nexus_repos_docker_proxy }}'

- include_tasks: '{{ NEXUS_ROLE_PATH }}/tasks/create_repo_docker_group_each.yml'
  with_items: '{{ nexus_repos_docker_group }}'