---
- name: 'Generate certificates for nexus'
  include_role:
    name: certificate
  vars:
    CERT_NAME: '{{ NEXUS_NAME }}'

- name: 'Install containers'
  docker_service:
    project_name: '{{ NEXUS_NAME }}'
    definition:
      version: '3.5'
      networks: '{{ NEXUS_NETWORK | default(omit) }}'
      services:
        nexus:
          image: 'bradbeck/nexus-https:latest'
          container_name: '{{ NEXUS_NAME }}'
          ports:
            - '{{ NEXUS_HTTP_PORT }}:8081'
            - '{{ NEXUS_HTTPS_PORT }}:8443'
            - '{{ NEXUS_DOCKER_PORT }}:9082'
          volumes:
            - '{{ NEXUS_DATASTORE }}:/sonatype-work'
          environment:
            - 'PUBLIC_CERT=/run/secrets/nexus.crt'
            - 'PRIVATE_KEY=/run/secrets/nexus.pem'
          secrets:
            - 'nexus.crt'
            - 'nexus.pem'
            - 'ca.crt'
          restart: always
      secrets:
        nexus.crt:
          file: '{{ NEXUS_CRT }}'
        nexus.pem:
          file: '{{ NEXUS_PRIVATEKEY }}'
        ca.crt:
          file: '{{ NEXUS_CA }}'

- name: 'Wait for Nexus to come up'
  uri:
    url: 'http://127.0.0.1:{{ NEXUS_HTTP_PORT }}'
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 5

- name: 'Get ansible-nexus3-oss role'
  command: 'ansible-galaxy install {{ NEXUS_ROLE_SOURCE }} -p {{ NEXUS_ROLE_PATH | dirname }}'

- include_tasks: configure.yml
  tags: test