---
LDAP_ADMIN_NAME: 'ldap-admin'
LDAP_ADMIN_HTTP: 8083
LDAP_ADMIN_HTTPS: 8084
LDAP_ADMIN_CRT: '/etc/ssl/crt/{{ LDAP_ADMIN_NAME }}.crt'
LDAP_ADMIN_PRIVATEKEY: '/etc/ssl/private/{{ LDAP_ADMIN_NAME }}.pem'
LDAP_ADMIN_CA: '/etc/ssl/crt/ca.crt'
LDAP_ADMIN_PASSWORD: 'TopS3cr3t'
LDAP_ADMIN_NETWORK:       
  default:
    external:
      name: homelab-network

LDAP_ADMIN_CONFIG:       
  - 'ldap':
    - server:
      - tls: true
    - login:
      - bind_id: 'cn=administrator,cn=users,dc=example,dc=com'
      - bind_pass: '{{ LDAP_ADMIN_PASSWORD }}'