- hosts: localhost
  connection: local
  become: yes
  pre_tasks:
    - name: 'Update all packages'
      apt:
        update_cache: yes
        upgrade: dist

    - name: 'Install python and pip'
      tags: test
      apt:
        name: 'python-pip,libsasl2-dev,python-dev,libldap2-dev,libssl-dev'
        
    - name: 'Install python dependencies'
      tags: test
      pip:
        name: 'docker,docker-compose,python-ldap'

    - name: 'Create homelab network'
      docker_network:
        name: 'homelab-network'
        driver: 'bridge'
        ipam_options:
          subnet: '172.18.0.0/16'
          gateway: '172.18.0.1'        
  roles:
    - { role: 'certificate', CERT_NAME: 'nexus' }
    - { role: 'certificate', CERT_NAME: 'ldap' }
    - { role: 'certificate', CERT_NAME: 'ldap-admin' }
    - { role: 'certificate', CERT_NAME: 'consul' }
    - { role: 'certificate', CERT_NAME: 'vault' }
    - { role: 'certificate', CERT_NAME: 'artifacts' }
    - { role: 'certificate', CERT_NAME: 'gitea' }
    - { role: 'samba-domain' }
    - { role: 'ldap-admin' }
    - { role: 'sample_ad_data' }
    - { role: 'nexus3' }
    - { role: 'consul' }
    - { role: 'vault' }
    - { role: 'artifactory' }
    - { role: 'gitea' }
    #- jenkins-master WIP