- hosts: localhost
  connection: local
  become: yes
  pre_tasks:
    - name: 'Update all packages'
      apt:
        update_cache: yes
        upgrade: dist

    - name: 'Install python and pip'
      tags: test
      apt:
        name: 'python-pip,libsasl2-dev,python-dev,libldap2-dev,libssl-dev'
        
    - name: 'Install python dependencies'
      tags: test
      pip:
        name: 'docker,docker-compose,python-ldap'

    - name: 'Create homelab network'
      docker_network:
        name: 'homelab-network'
        driver: 'bridge'
        ipam_options:
          subnet: '172.18.0.0/16'
          gateway: '172.18.0.1'        
  roles:
    - samba-domain
    - ldap-admin
    - sample_ad_data
    - consul
    - vault
    - artifactory
    - nexus3
    - gitea
    #- jenkins-master WIP