- hosts: localhost
  connection: local
  become: yes
  pre_tasks:
    - name: 'Create additional disk'
      parted:
        device: /dev/sdc
        flags: [ lvm ]
        number: '2'
        part_start: '{{ item.start }}'
        part_end: '{{ item.end }}'
        state: present
      with_items:
        - { start: '0%', end: '10GiB' }
        - { start: '10GiB', end: '100%' }
          
    - name: 'Format new partitions as ext4'
      filesystem:
        fstype: 'ext4'
        dev: '{{ item }}'
      with_items:
        - '/dev/sdc1'
        - '/dev/sdc2'
          
    - name: 'Mount the new partitions'
      mount:
        fstype: 'ext4'
        src: '{{ item.src }}'
        path: '{{ item.dest }}'
        state: 'mounted'
      with_items:
        - { src: '/dev/sdc1', dest: '/data' }
        - { src: '/dev/sdc2', dest: '/mnt/docker' }
    
    - name: 'Configure docker daemon'
      copy:
        content: '{ "data-root": "/mnt/docker" }'
        dest: '/etc/docker/daemon.json'
        owner: 'root'
        group: 'root'
        mode: '0644'
      register: docker_cfg
       
    - name: 'Restart docker deamon'
      when: 'docker_cfg is changed'
      service: 
        name: 'docker'
        state: 'restarted'
  
    - name: 'Update all packages'
      apt:
        update_cache: yes
        upgrade: dist

    - name: 'Install python and pip'
      apt:
        name: 'python-pip,libsasl2-dev,python-dev,libldap2-dev,libssl-dev'
        
    - name: 'Install python dependencies'
      pip:
        name: 'docker,docker-compose,python-ldap'

    - name: 'Create homelab network'
      docker_network:
        name: 'homelab-network'
        driver: 'bridge'
        ipam_options:
          subnet: '172.18.0.0/16'
          gateway: '172.18.0.1'        
  roles:
    - role: certificate
      CERT_NAME: 'nexus'
      CERT_PATH: '{{ NEXUS_CRT }}'
      CERT_PRIVATEKEY: '{{ NEXUS_PRIVATEKEY }}'
    - role: certificate
      CERT_NAME: 'ldap'
      CERT_PATH: '{{ SAMBA_CRT }}'
      CERT_PRIVATEKEY: '{{ SAMBA_PRIVATEKEY }}'
    - role: certificate
      CERT_NAME: 'ldap-admin'
      CERT_PATH: '{{ LDAP_ADMIN_CRT }}'
      CERT_PRIVATEKEY: '{{ LDAP_ADMIN_PRIVATEKEY }}'
    - role: certificate
      CERT_NAME: 'consul'        
    - role: certificate
      CERT_NAME: 'vault'
      CERT_PATH: '{{ VAULT_CERT }}'
      CERT_PRIVATEKEY: '{{ VAULT_PRIVATEKEY }}'             
    - role: certificate
      CERT_NAME: 'artifacts'        
    - role: certificate
      CERT_NAME: 'gitea'
    - { role: 'samba-domain' }
    - { role: 'ldap-admin' }
    - { role: 'sample_ad_data' }
    - { role: 'nexus3' }
    - { role: 'consul' }
    - { role: 'vault' }
    - { role: 'artifactory' }
    - { role: 'gitea' }
    - { role: 'jenkins-master' }