---
LDAP_NAME: 'ldap'
LDAP_NETWORK:       
  default:
    external:
      name: homelab-network
LDAP_ORGANISATION: 'Test Environment'
LDAP_DOMAIN: 'example.com'
LDAP_ADMIN_PASSWORD: 'test'
LDAP_CRT: '/etc/ssl/crt/{{ LDAP_NAME }}.crt'
LDAP_PRIVATEKEY: '/etc/ssl/private/{{ LDAP_NAME }}.pem'
LDAP_CA: '/etc/ssl/crt/ca.crt'
LDAP_SEED_FILE: '/vagrant/data/'
LDAP_PORT: 389
LDAPS_PORT: 636