---
- name: 'Generate certificates for ldap-admin'
  include_role:
    name: certificate
  vars:
    CERT_NAME: '{{ LDAP_ADMIN_NAME }}'

- name: 'Install containers'
  docker_service:
    project_name: '{{ LDAP_ADMIN_NAME }}'
    definition:
      version: '3.5'
      networks: '{{ LDAP_ADMIN_NETWORK | default(omit) }}'
      services:
        ldap-admin:
          image: 'mwaeckerlin/lam'
          container_name: '{{ LDAP_ADMIN_NAME }}'
          ports:
            - '{{ LDAP_ADMIN_HTTP }}:80'           
          restart: 'always'

