- name: 'Install openSSL package'
  package: 
    name: 'openssl'
    state: 'present'

- name: 'Create directories'
  file:
    path: '{{ item }}'
    state: 'directory'
  with_items:
    - '{{ CA_CERT_HOME }}'
    - '{{ CA_PRIVATEKEY_HOME }}'
    - '{{ CERT_HOME }}'
    - '{{ CERT_PRIVATEKEY_HOME }}'
    - '{{ CERT_CSR_HOME }}'

- name: 'Generate CA certificate'
  command: 'openssl req -new -newkey rsa:{{ CA_KEYSIZE | int }} -days {{ CA_VALIDITY | int }} -nodes -x509 -subj "{{ CA_SUBJECT }}" -keyout {{ CA_PRIVATEKEY }} -out {{ CA_CERT }}'
  args:
    creates: '{{ CA_CERT }}'
    
- name: 'Generate private key'
  command: 'openssl genrsa -out {{ CERT_PRIVATEKEY }} {{ CERT_KEYSIZE | int }}'
  args:
    creates: '{{ CERT_PRIVATEKEY }}'
    
- name: 'Generate CSR'
  command: 'openssl req -new -sha512 -key {{ CERT_PRIVATEKEY }} -subj "{{ CERT_SUBJECT }}" -out {{ CERT_CSR }}'
  args:
    creates: '{{ CERT_CSR }}'
    
- name: 'Generate certificate from CSR'
  command: 'openssl x509 -req -in {{ CERT_CSR }} -CA {{ CA_CERT }} -CAkey {{ CA_PRIVATEKEY }} -CAcreateserial -out {{ CERT_PATH }} -days {{ CERT_VALIDITY }} -sha512'
  args:
    creates: '{{ CERT_PATH }}'
  register: cert_result

- name: 'Bundle certificate'
  when: 'cert_result is changed'
  shell: 'cat {{ CA_CERT }} >> {{ CERT_PATH }}'