- command: "docker exec vault vault write auth/userpass/users/jenkins password=jenkins policies=admins"
- command: "docker exec vault vault write secret/jenkins/master LDAP_USER=admin LDAP_PASSWORD=test ARTIFACTORY_USER=can ARTIFACTORY_PASSWORD=test GITEA_USER=can GITEA_PASSWORD=test"                     

    - docker_service:
        project_name: repositories
        definition:
          version: '3.5'
          networks:
            default:
              external:
                name: homelab-network     
          services:
            jenkins-master:
              build: /vagrant/jenkins-master
              image: jenkins-master
              container_name: jenkins-master
              ports:
                - "8080:8080"
                - "50000:50000"
              volumes:
                - "/var/run/docker.sock:/var/run/docker.sock"
                - "/mnt/host_files/.output:/certs"
              environment:
                - "DOCKER_REGISTRY_URL=https://docker-registry:5000/v2/"
                - "CASC_VAULT_PW=jenkins"
                - "CASC_VAULT_USER=jenkins"
                - "CASC_VAULT_PATH=secret/jenkins/master"
                - "CASC_VAULT_URL=https://vault:8200" 
                - "JAVA_OPTS=-Djava.util.logging.loglevel=FINE"
                - "ORGANIZATION_NAME=J2H"
              restart: always