---
- name: 'Generate certificates'
  include_role:
    name: certificate
  vars:
    CERT_NAME: '{{ DOCKER_REG }}'

- name: 'Create directory for docker-registry certificate'
  file: 
    path: '{{ DOCKER_REG_CA_CERT_DEST }}'
    state: 'directory'
    
- name: 'Copy CA certificate to docker'
  copy:
    src: '{{ DOCKER_REG_CA_CERT }}'
    dest: '{{ DOCKER_REG_CA_CERT_DEST }}/ca.crt'
    remote_src: yes
    
- name: 'Added docker registry to hosts file'
  lineinfile:
    path: '/etc/hosts'
    line: '{{ DOCKER_REG_IP }} {{ DOCKER_REG }}'
    
- docker_service:
    project_name: '{{ DOCKER_REG }}'
    definition:
      version: '3.5'
      networks: '{{ DOCKER_REG_NETWORK | default(omit) }}'
      services:
        docker-registry:
          image: 'registry:2'
          container_name: '{{ DOCKER_REG }}'
          ports:
            - '{{ DOCKER_REG_PORT }}:5000'
          volumes:
            - '{{ DOCKER_REG_DATASTORE }}:/var/lib/registry'
          environment:
            - 'REGISTRY_HTTP_TLS_CERTIFICATE=/run/secrets/docker-registry.crt'
            - 'REGISTRY_HTTP_TLS_KEY=/run/secrets/docker-registry.pem'
          secrets:
            - 'docker-registry.crt'
            - 'docker-registry.pem'
          restart: always
      secrets:
        docker-registry.crt:
          file: '{{ DOCKER_REG_CRT }}'
        docker-registry.pem:
          file: '{{ DOCKER_REG_KEY }}'