---
VAULT_NAME: 'vault'
VAULT_PORT: 8200
VAULT_CACERT: '/etc/ssl/crt/ca.crt'
VAULT_CERT: '/etc/ssl/crt/{{ VAULT_NAME }}.crt'
VAULT_PRIVATEKEY: '/etc/ssl/private/{{ VAULT_NAME }}.pem'
VAULT_CONSUL_ADDR: 'consul:8500'
VAULT_CONSUL_ADVERTISE_ADDR: 'http://consul:8300'
VAULT_CONSUL_PATH: '{{ VAULT_NAME }}/'
VAULT_CONFIG:
  backend: 
    consul:
      address: '{{ VAULT_CONSUL_ADDR }}'
      advertise_addr: '{{ VAULT_CONSUL_ADVERTISE_ADDR }}'
      path: '{{ VAULT_CONSUL_PATH }}'
  listener:
    tcp:
      address: '0.0.0.0:{{ VAULT_PORT }}'
      tls_cert_file: '/run/secrets/vault.crt'
      tls_key_file: '/run/secrets/vault.pem'

VAULT_AUTH_METHODS:
  - userpass