---
- name: 'Configure datastore'
  file: 
    dest: '{{ ARTIFACTORY_DATASTORE }}'
    owner: 1030
    group: 'root'
    mode: 0775
    recurse: yes

- name: 'Create etc folder'
  file: 
    path: '{{ ARTIFACTORY_DATASTORE }}/etc'
    owner: 1030
    group: 'root'
    mode: 0777    
    state: 'directory'
    
- name: 'Create inital configuration file'
  template: 
    src: 'templates/artifactory.config.import.yml.jinja2'
    dest: '{{ ARTIFACTORY_DATASTORE }}/etc/artifactory.config.import.yml'   
    
- name: 'Create container for Artifactory'
  docker_service:
    project_name: '{{ ARTIFACTORY_NAME }}'
    definition:
      version: '3.5'
      networks: '{{ ARTIFACTORY_NETWORK | default(omit) }}'
      services:
        artifactory:
          image: 'docker.bintray.io/jfrog/artifactory-oss:6.3.3'
          container_name: '{{ ARTIFACTORY_NAME }}'
          ports:
           - '{{ ARTIFACTORY_PORT }}:8081'
          volumes:
           - '{{ ARTIFACTORY_DATASTORE }}:/var/opt/jfrog/artifactory'
          restart: always
          ulimits:
            nproc: 65535
            nofile:
              soft: 32000
              hard: 40000               

- name: 'Wait for Artifactory to come up'
  uri:
    url: 'http://127.0.0.1:{{ ARTIFACTORY_PORT }}/artifactory/api/system/ping'
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
  
- name: 'Change admin password'
  uri:
    url: 'http://127.0.0.1:{{ ARTIFACTORY_PORT }}/artifactory/api/security/users/authorization/changePassword'
    method: 'POST'
    body:
      userName: 'admin'
      oldPassword: 'password'
      newPassword1: '{{ ARTIFACTORY_PASSWORD }}'
      newPassword2: '{{ ARTIFACTORY_PASSWORD }}'
    body_format: 'json'   
    status_code: 200, 400
  register: result
  changed_when: 'result.status == 200'
  
- name: 'Create default repos'
  uri:
    url: 'http://127.0.0.1:{{ ARTIFACTORY_PORT }}/artifactory/ui/onboarding/createDefaultRepos'
    method: 'POST'
    body:
      repoTypeList:
        - Generic
      fromOnboarding: true
    body_format: 'json'
    status_code: 201
    return_content: yes
    force_basic_auth: true
    user: 'admin'
    password: '{{ ARTIFACTORY_PASSWORD }}'